const Constants = {
  PULL_REQUEST_DETAILS_FETCHED: 'PULL_REQUEST_DETAILS_FETCHED',
  FILES_INFO_FETCHED: 'FILES_INFO_FETCHED',
  IZUNA_APP_DONE: 'IZUNA_APP_DONE',

  IZUNA_HOST_URL: 'https://izuna.app',

  ENABLE_IZUNA_KEY: 'IZUNA',

  LEFT_LOCATION: 'LEFT',
  CENTER_LOCATION: 'CENTER',
  RIGHT_LOCATION: 'RIGHT',

  IZUNA_HIGHLIGHT_REGION: 'izuna-highlighted-region',
};

export { Constants };
